### ISSUE TITLE
chrono displacer crash 2

### ISSUE THREAD

**Issue by wesleybruce** [ZenDarva/Parachronography#2]
This is the one on the wastelands map. Some blocks around the displacer but a wastelands block under it. When I came back in in both cases the ores were there as expected. Could it be messing with walla? 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 3/14/16 8:24 PM
Description: Unexpected error

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at com.darva.parachronology.utility.Scheduler.runTasks(Scheduler.java:120)
    at com.darva.parachronology.utility.Scheduler.onClientTick(Scheduler.java:113)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_Scheduler_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at com.darva.parachronology.utility.Scheduler.runTasks(Scheduler.java:120)
    at com.darva.parachronology.utility.Scheduler.onClientTick(Scheduler.java:113)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_Scheduler_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['wes_bruce'/0, l='MpServer', x=2053.39, y=55.00, z=-1163.14]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 07 - ezwastelands, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: 2066.00,50.00,-1159.00 - World: (2066,50,-1159), Chunk: (at 2,3,9 in 129,-73; contains blocks 2064,0,-1168 to 2079,255,-1153), Region: (4,-3; contains chunks 128,-96 to 159,-65, blocks 2048,0,-1536 to 2559,255,-1025)
    Level time: 52826 game time, 36433 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 4 total; [EntityPlayerSP['wes_bruce'/0, l='MpServer', x=2053.39, y=55.00, z=-1163.14], EntityItem['item.tile.sapling.oak'/2961959, l='MpServer', x=2058.66, y=52.00, z=-1164.00], EntityItem['item.tile.sapling.oak'/2939245, l='MpServer', x=2058.88, y=56.00, z=-1170.47], EntityItem['item.item.apple'/2944077, l='MpServer', x=2060.94, y=53.00, z=-1169.38]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 266506336 bytes (254 MB) / 1386217472 bytes (1322 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 13, tcache: 95, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 12 mods loaded, 12 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   ezwastelands{0.9.0} [EzWastelands](ezwastelands-1.8.9-0.9.0.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-39-eae6253} [Inventory Tweaks](InventoryTweaks-1.60-beta-39.jar) 
    UCHIJAAAA   JEI{2.28.7.174} [Just Enough Items](jei_1.8.9-2.28.7.174.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons](JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.1.5} [JourneyMap](journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJAAAA   llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
    UCHIJAAAA   parachronology{0.1.6} [parachronology](Parachronology-0.2.4.1.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
    Launched Version: forge-11.15.1.1764
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4331, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
```

**Comment by ZenDarva** [comment]
Fixed by commit # 7d7ada8b4ad5cab094b0c6fe63ec0b9d27599423
